### ISSUE TITLE
Plan pricing varies with diaper sizes

### ISSUE THREAD

**Issue by stgogm** [FinalDevStudio/club-panales#10]

**Comment by stgogm** [comment]
@jtguzman Need to clarify if it will depend on a factor, base price or something else according to diaper size as it directly affects data model and functionality.

**Comment by jtguzman** [comment]
The client sent this, is this enough?

![unnamed](https://cloud.githubusercontent.com/assets/3739603/12625446/a0226168-c512-11e5-9048-c910462ab4e8.png)

**Comment by stgogm** [comment]
It's enough. Thanks.
